const palavras = [
  { palavra: "abacaxi", dica: "Fruta tropical" },
  { palavra: "elefante", dica: "Animal de grande porte com tromba longa" },
  { palavra: "computador", dica: "Dispositivo eletrônico" },
  { palavra: "girafa", dica: "Animal alto, com pescoço longo" },
  { palavra: "chocolate", dica: "Doce feito de cacau" },
  { palavra: "piano", dica: "Instrumento musical com teclas" },
  { palavra: "tigre", dica: "Felino selvagem" },
  { palavra: "esmeralda", dica: "Tipo de pedra preciosa" },
  { palavra: "navio", dica: "Embarcação no mar" },
  { palavra: "telefone", dica: "Dispositivo de comunicação" },
  { palavra: "floresta", dica: "Área com muitas árvores" },
  { palavra: "cachorro", dica: "Melhor amigo do homem" },
  { palavra: "internet", dica: "Rede mundial de computadores" },
  { palavra: "caneta", dica: "Usada para escrever" },
  { palavra: "televisao", dica: "Aparelho para assistir programas" },
  { palavra: "banana", dica: "Fruta amarela" },
  { palavra: "carro", dica: "Meio de transporte com quatro rodas" },
  { palavra: "aviao", dica: "Meio de transporte aéreo" },
  { palavra: "livro", dica: "Conjunto de páginas encadernadas" },
  { palavra: "oceano", dica: "Grande massa de água salgada" },
  { palavra: "satelite", dica: "Objeto que orbita a Terra" },
  { palavra: "bicicleta", dica: "Meio de transporte com duas rodas" },
  { palavra: "jacare", dica: "Réptil encontrado em rios e pântanos" },
  { palavra: "sol", dica: "Estrela que ilumina o dia" },
  { palavra: "lua", dica: "Satélite natural da Terra" },
  { palavra: "estrela", dica: "Corpo celeste que brilha no céu" },
  { palavra: "lampada", dica: "Dispositivo que emite luz" },
  { palavra: "relogio", dica: "Objeto que mede o tempo" },
  { palavra: "papel", dica: "Material usado para escrever" },
  { palavra: "porta", dica: "Objeto que abre e fecha, usado em entradas" },
  { palavra: "cavalo", dica: "Animal usado para montaria" },
  { palavra: "prato", dica: "Usado para servir comida" },
  { palavra: "ventilador", dica: "Aparelho usado para ventilar" },
  { palavra: "cadeira", dica: "Usado para sentar" },
  { palavra: "maca", dica: "Fruta vermelha e saudável" },
  { palavra: "uva", dica: "Fruta usada para fazer vinho" },
  { palavra: "formiga", dica: "Inseto que vive em colônias" },
  { palavra: "arvore", dica: "Planta alta com tronco e folhas" },
  { palavra: "peixe", dica: "Animal que vive na água" },
  { palavra: "tartaruga", dica: "Réptil com casco" },
  { palavra: "borboleta", dica: "Inseto com asas coloridas" },
  { palavra: "foguete", dica: "Veículo que vai ao espaço" },
  { palavra: "quadro", dica: "Objeto usado para pendurar na parede" },
  { palavra: "boneca", dica: "Brinquedo que imita um bebê" },
  { palavra: "geladeira", dica: "Aparelho usado para conservar alimentos" },
  { palavra: "garrafa", dica: "Recipiente usado para armazenar líquidos" },
  { palavra: "radio", dica: "Aparelho usado para ouvir música e notícias" },
  { palavra: "travesseiro", dica: "Usado para apoiar a cabeça ao dormir" },
  { palavra: "sapo", dica: "Anfíbio que pula e croa" },
  { palavra: "panela", dica: "Usada para cozinhar alimentos" },
  { palavra: "escola", dica: "Lugar onde se aprende" },
  { palavra: "camisa", dica: "Roupa usada na parte de cima do corpo" },
  { palavra: "calca", dica: "Roupa usada nas pernas" },
  { palavra: "chave", dica: "Usada para abrir fechaduras" },
  { palavra: "colher", dica: "Talher usado para sopas e sobremesas" },
  { palavra: "pimenta", dica: "Condimento picante" },
  { palavra: "cereja", dica: "Pequena fruta vermelha" },
  { palavra: "leao", dica: "O rei da selva" },
  { palavra: "joaninha", dica: "Inseto pequeno com asas vermelhas e pintas pretas" },
  { palavra: "pirata", dica: "Ladrão dos mares" },
  { palavra: "tesoura", dica: "Usada para cortar" },
  { palavra: "violino", dica: "Instrumento musical de cordas" },
  { palavra: "dragao", dica: "Criatura mítica que cospe fogo" },
  { palavra: "lobo", dica: "Animal selvagem semelhante a um cachorro" },
  { palavra: "girassol", dica: "Flor amarela que segue o sol" },
  { palavra: "morango", dica: "Fruta vermelha com sementes externas" },
  { palavra: "esquilo", dica: "Animal que gosta de nozes" },
  { palavra: "vulcao", dica: "Montanha que cospe lava" },
  { palavra: "fantasma", dica: "Espírito assustador" },
  { palavra: "algodao", dica: "Fibra branca usada em roupas" },
  { palavra: "camelo", dica: "Animal que vive no deserto" },
  { palavra: "microscopio", dica: "Aparelho usado para ver pequenos organismos" },
  { palavra: "rato", dica: "Pequeno roedor" },
  { palavra: "ovelha", dica: "Animal que fornece lã" },
  { palavra: "tigre", dica: "Felino selvagem" },
  { palavra: "serpente", dica: "Reptil que rasteja" },
  { palavra: "praia", dica: "Faixa de areia junto ao mar" },
  { palavra: "vaca", dica: "Animal que fornece leite" },
  { palavra: "guitarra", dica: "Instrumento musical de cordas" },
  { palavra: "farol", dica: "Construção à beira-mar que orienta navios" },
  { palavra: "canguru", dica: "Animal que salta e tem uma bolsa" },
  { palavra: "martelo", dica: "Ferramenta usada para bater" },
  { palavra: "relampago", dica: "Fenômeno elétrico no céu" },
  { palavra: "chaveiro", dica: "Usado para carregar chaves" },
  { palavra: "polvo", dica: "Animal marinho com oito tentáculos" },
  { palavra: "geleia", dica: "Doce feito de frutas" },
  { palavra: "folha", dica: "Parte da planta que faz fotossíntese" },
  { palavra: "cebola", dica: "Legume que faz as pessoas chorarem ao cortar" },
  { palavra: "cimento", dica: "Material de construção para unir tijolos" },
  { palavra: "cisne", dica: "Ave elegante com pescoço longo" },
  { palavra: "pingente", dica: "Peça pendurada em colares" },
  { palavra: "anel", dica: "Joia usada nos dedos" },
  { palavra: "zebra", dica: "Animal com listras brancas e pretas" },
  { palavra: "trator", dica: "Máquina usada em fazendas" },
  { palavra: "tijolo", dica: "Bloco usado em construções" },
  { palavra: "baleia", dica: "O maior mamífero marinho" },
  { palavra: "canguru", dica: "Animal que pula e tem uma bolsa" },
  { palavra: "magneto", dica: "Objeto que atrai metais" },
  { palavra: "iceberg", dica: "Grande bloco de gelo flutuante" },
  { palavra: "escada", dica: "Usada para alcançar lugares altos" },
  { palavra: "abismo", dica: "Lugar profundo e escuro" },
  { palavra: "relampago", dica: "Evento natural que ocorre antes do trovão" },
  { palavra: "miragem", dica: "Ilusão ótica causada pelo calor" },
  { palavra: "oxigenio", dica: "Elemento essencial à respiração, mas invisível" },
  { palavra: "enigmatico", dica: "Algo difícil de decifrar" },
  { palavra: "paradoxo", dica: "Afirmação aparentemente contraditória" },
  { palavra: "crepusculo", dica: "Momento entre o pôr do sol e a escuridão" },
  { palavra: "catedral", dica: "Grande construção religiosa" },
  { palavra: "otorrinolaringologista", dica: "Especialista em ouvido, nariz e garganta" },
  { palavra: "anticiclone", dica: "Fenômeno meteorológico associado ao tempo seco" },
  { palavra: "barometro", dica: "Instrumento para medir a pressão atmosférica" },
  { palavra: "dodecafonismo", dica: "Técnica musical baseada em uma escala de 12 tons" },
  { palavra: "criptografia", dica: "Técnica usada para ocultar informações" },
  { palavra: "inexoravel", dica: "Algo que não pode ser detido ou evitado" },
  { palavra: "triangulacao", dica: "Método de localização baseado em três pontos de referência" },
  { palavra: "subterraneo", dica: "Que se encontra abaixo da superfície" },
  { palavra: "anacronismo", dica: "Erro cronológico, algo fora de seu tempo" },
  { palavra: "subestimar", dica: "Ação de julgar algo como menor do que realmente é" },
  { palavra: "quimera", dica: "Criatura mitológica composta de diferentes animais" },
  { palavra: "meticulosidade", dica: "Ato de fazer algo com extremo cuidado e atenção aos detalhes" },
  { palavra: "efemero", dica: "Algo que tem curta duração" },
  { palavra: "monolitico", dica: "Sólido e uniforme, sem divisões" },
  { palavra: "cacofonia", dica: "Combinação de sons desagradáveis" },
  { palavra: "dissonancia", dica: "Falta de harmonia entre elementos" },
  { palavra: "contraditorio", dica: "Que apresenta ideias opostas entre si" },
  { palavra: "enigmatico", dica: "Algo ou alguém que é difícil de entender" },
  { palavra: "dissonante", dica: "Algo que não se encaixa, em desacordo" },
  { palavra: "labirinto", dica: "Estrutura complexa com muitos caminhos e poucas saídas" },
  { palavra: "perpendicular", dica: "Que forma um ângulo reto com outra linha ou superfície" },
  { palavra: "clandestino", dica: "Que ocorre em segredo ou ilegalmente" },
  { palavra: "intransponivel", dica: "Impossível de ultrapassar" },
  { palavra: "fugaz", dica: "Algo que passa rápido, breve" },
  { palavra: "ataraxia", dica: "Estado de tranquilidade plena" },
  { palavra: "prerrogativa", dica: "Direito ou privilégio exclusivo" },
  { palavra: "voraz", dica: "Que tem grande apetite ou desejo insaciável" },
  { palavra: "carpe diem", dica: "Expressão que incentiva a aproveitar o momento" },
  { palavra: "metafisico", dica: "Relacionada à filosofia do ser e do existir" },
  { palavra: "paradigma", dica: "Modelo ou padrão de referência" },
  { palavra: "ubiquidade", dica: "Capacidade de estar presente em vários lugares ao mesmo tempo" },
  { palavra: "incongruente", dica: "Algo que não combina ou faz sentido no contexto" },
  { palavra: "atavico", dica: "Relativo a traços herdados de ancestrais" },
  { palavra: "oximoro", dica: "Figura de linguagem que une termos contraditórios" },
  { palavra: "antipoda", dica: "Que se encontra exatamente no ponto oposto de outro lugar no globo" },
  { palavra: "arcano", dica: "Algo misterioso e secreto" },
  { palavra: "ataraxia", dica: "Estado de serenidade e ausência de perturbação" },
  { palavra: "onirico", dica: "Relativo aos sonhos" },
  { palavra: "transcendental", dica: "Algo que vai além da experiência comum" },
  { palavra: "efervescente", dica: "Que produz borbulhas ou grande animação" },
  { palavra: "pleonasmo", dica: "Uso de palavras redundantes para reforçar uma ideia" },
  { palavra: "melancolia", dica: "Tristeza profunda e prolongada" },
  { palavra: "subjacente", dica: "Que está implícito ou sob algo" },
  { palavra: "idiossincrasia", dica: "Traço ou característica única de uma pessoa ou coisa" },
  { palavra: "espectro", dica: "Imagem ou visão associada a fantasmas ou um intervalo contínuo" },
  { palavra: "axioma", dica: "Uma verdade inquestionável usada como base para raciocínios" },
  { palavra: "paradigma", dica: "Modelo ou exemplo que serve de padrão" },
  { palavra: "inverossimil", dica: "Algo que parece improvável ou difícil de acreditar" },
  { palavra: "inexoravel", dica: "Que não pode ser detido ou modificado" },
  { palavra: "palindrome", dica: "Palavra ou frase que pode ser lida da mesma forma de trás para frente" },
  { palavra: "sublime", dica: "Extremamente belo ou grandioso" },
  { palavra: "decadente", dica: "Que está em processo de declínio" },
  { palavra: "empirico", dica: "Baseado em experiência ou observação" },
  { palavra: "imperioso", dica: "Algo que é necessário ou urgente" },
  { palavra: "ludico", dica: "Relacionado a jogos ou brincadeiras" },
  { palavra: "verossimil", dica: "Que parece ser verdadeiro ou plausível" },
  { palavra: "mutabilidade", dica: "Capacidade de mudar ou ser alterado" },
  { palavra: "paradigma", dica: "Modelo ou padrão que serve de referência" },
  { palavra: "polarizacao", dica: "Divisão em dois extremos opostos" },
  { palavra: "periferia", dica: "Área ao redor de uma região central" },
  { palavra: "elucidar", dica: "Esclarecer ou tornar algo claro" },
  { palavra: "ignominia", dica: "Desonra ou vergonha extrema" },
  { palavra: "inercial", dica: "Relacionado ao princípio da inércia" },
  { palavra: "hermetico", dica: "Fechado de forma que nada possa sair ou entrar" },
  { palavra: "pernicioso", dica: "Extremamente prejudicial ou destrutivo" },
  { palavra: "retratil", dica: "Capaz de ser recolhido ou retraído" },
  { palavra: "impavido", dica: "Que não sente medo; destemido" },
  { palavra: "espectro", dica: "Imagem, especialmente a de um fantasma" },
  { palavra: "imponderavel", dica: "Algo que não pode ser previsto ou medido" },
  { palavra: "ontologico", dica: "Relacionado ao estudo do ser e da existência" },
  { palavra: "vexatorio", dica: "Algo que causa constrangimento ou humilhação" },
  { palavra: "sibilante", dica: "Som caracterizado pelo chiado" },
  { palavra: "hieratico", dica: "Solene e formal, especialmente em rituais" },
  { palavra: "meticuloso", dica: "Que presta extrema atenção aos detalhes" },
  { palavra: "silogismo", dica: "Forma de argumento lógico com duas premissas e uma conclusão" },
  { palavra: "corrosivo", dica: "Que causa desgaste ou destruição gradual" },
  { palavra: "lucidez", dica: "Estado de clareza mental" },
  { palavra: "vicissitude", dica: "Mudança ou variação que ocorre com o tempo" },
  { palavra: "periplo", dica: "Viagem longa e cheia de eventos" },
  { palavra: "veracidade", dica: "Qualidade de ser verdadeiro ou fiel aos fatos" },
  { palavra: "assonancia", dica: "Repetição de sons semelhantes, especialmente vogais" },
  { palavra: "indolente", dica: "Alguém que evita esforço ou é apático" }
];

export default function pegarPalavra() {
  const index = Math.floor(Math.random() * palavras.length);
  return palavras[index];
};